# Do NOT update manually; changes here will be overwritten by Copier
_commit: 25861d8
_src_path: gh:open-synergy/ssi-addons-repo-template
dependency_installation_mode: OCA
generate_requirements_txt: true
include_aeroo_report: false
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: ssi-mixin
repo_name: ssi-mixin
repo_slug: ssi-mixin
travis_apt_packages: []
travis_apt_sources: []
