[project]
name = "odoo-addons-open-synergy-ssi-mixin"
version = "19.0.20260718.32"
dependencies = [
    "odoo-addon-ssi_backend_mixin==19.0.*",
    "odoo-addon-ssi_company_currency_mixin==19.0.*",
    "odoo-addon-ssi_custom_information_mixin==19.0.*",
    "odoo-addon-ssi_decorator==19.0.*",
    "odoo-addon-ssi_localdict_mixin==19.0.*",
    "odoo-addon-ssi_m2o_configurator_mixin==19.0.*",
    "odoo-addon-ssi_master_data_mixin==19.0.*",
    "odoo-addon-ssi_multiple_approval_mixin==19.0.*",
    "odoo-addon-ssi_partner_mixin==19.0.*",
    "odoo-addon-ssi_policy_mixin==19.0.*",
    "odoo-addon-ssi_print_mixin==19.0.*",
    "odoo-addon-ssi_qr_code_mixin==19.0.*",
    "odoo-addon-ssi_reference_document_mixin==19.0.*",
    "odoo-addon-ssi_related_attachment_mixin==19.0.*",
    "odoo-addon-ssi_sequence_mixin==19.0.*",
    "odoo-addon-ssi_source_document_mixin==19.0.*",
    "odoo-addon-ssi_state_change_constrain_mixin==19.0.*",
    "odoo-addon-ssi_state_change_history_mixin==19.0.*",
    "odoo-addon-ssi_status_check_mixin==19.0.*",
    "odoo-addon-ssi_tag_mixin==19.0.*",
    "odoo-addon-ssi_term_condition_mixin==19.0.*",
    "odoo-addon-ssi_transaction_cancel_mixin==19.0.*",
    "odoo-addon-ssi_transaction_confirm_mixin==19.0.*",
    "odoo-addon-ssi_transaction_date_duration_mixin==19.0.*",
    "odoo-addon-ssi_transaction_done_mixin==19.0.*",
    "odoo-addon-ssi_transaction_mixin==19.0.*",
    "odoo-addon-ssi_transaction_open_mixin==19.0.*",
    "odoo-addon-ssi_transaction_partner_mixin==19.0.*",
    "odoo-addon-ssi_transaction_ready_mixin==19.0.*",
    "odoo-addon-ssi_transaction_tax_address_mixin==19.0.*",
    "odoo-addon-ssi_transaction_terminate_mixin==19.0.*",
    "odoo-addon-ssi_transaction_total_mixin==19.0.*",
    "odoo-addon-ssi_transaction_win_lost_mixin==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
